### ISSUE TITLE
Desenvolvimento

### ISSUE THREAD

**Issue by jonerys** [trmendes/DadosD-moving-to-gitlab#1]
O app continuará a ser desenvolvido?

**Comment by trmendes** [comment]
Ola @jonerys. Sim. Mas estou viajando por alguns meses e estou sem computador. Assim que comprar um volto a desenvolver para colocar mais funcionalidades. Alguma sugestão?

**Comment by trmendes** [comment]
Mudando esse projeto para dentro do gitlab....@jonerys...se quiser me ajudar a desenvolver....sera super bem-vindo
